version: '3.8'

services:
  api-account:
    container_name: api-account
    build:
      context: .
      dockerfile: api-account/Dockerfile
    image: api-account
    command: sh -c "composer install && php -S 0.0.0.0:8080 -t /app/public -c php.ini"
    ports:
      - 8080:8080
    volumes:
      - ./api-account:/app
    env_file:
      - .env

  api-wallet:
    container_name: api-wallet
    build:
      context: .
      dockerfile: api-wallet/Dockerfile
    image: api-wallet
    command: sh -c "composer install && php -S 0.0.0.0:8080 -t /app/public -c php.ini"
    ports:
      - 8081:8080
    volumes:
      - ./api-wallet:/app
    env_file:
      - .env

  svc-bitcoind:
    container_name: svc-bitcoind
    build:
      context: .
      dockerfile: ./svc-bitcoind/Dockerfile
    image: svc-bitcoind
    ports:
      - '8332:8332'
      - '18332:18332'
    volumes:
      - /Users/daghan/bitcoin/testnet3:/root/bitcoin/data/testnet3

  svc-electrumx:
    container_name: svc-electrumx
    build:
      context: .
      dockerfile: ./svc-electrumx/Dockerfile
    image: svc-electrumx
    environment:
      - DAEMON_URL=http://${BTC_USER}:${BTC_PASS}@${BTC_HOST}:${BTC_PORT}
      - COIN=Bitcoin
      - NET=testnet
      - REORG_LIMIT=0
    ports:
      - '50001:50001'
      - '50002:50002'
      - '50004:50004'
      - '8000:8000'
    volumes:
      - /Users/daghan/electrumx:/data
    depends_on:
      - svc-bitcoind